### ISSUE TITLE
Add more instances

### ISSUE THREAD

**Issue by ozgurakgun** [conjure-cp/EssenceCatalog#5]
Another one @SeppiaBrilla - we have a few other repositories which contain instances that were never imported into this repository.

I'll give you a list and we should copy those instance into this repo for completeness.

**Comment by ozgurakgun** [comment]
Thanks to @ndangtt 

- Athanor: https://github.com/athanor/athanor-experiments/tree/master/aij2024
- Streamliner: https://github.com/stacs-cp/AIJ-streamliner/tree/master/InstanceGeneration

**Comment by SeppiaBrilla** [comment]
Hi @ozgurakgun, seems like the Streamliner link is broken, can you please double check it?

**Comment by ozgurakgun** [comment]
It’s a private repository, I’ll add you to it.

**Comment by ozgurakgun** [comment]
Done

**Comment by ozgurakgun** [comment]
Thanks a lot for all the work on this @SeppiaBrilla!
