### ISSUE TITLE
Missing Bin packing model

### ISSUE THREAD

**Issue by SeppiaBrilla** [conjure-cp/EssenceCatalog#6]
I've noticed that the catalogue has no model for the bin packing problem. We could use the one from the repository cited in issue #5 (from Athanor).

**Comment by ozgurakgun** [comment]
Yes please, let's create a new directory for bin packing. We can contribute this to the CSPLib as well at some point. There are a few problems that are in the EC but not on CSPLib already, so this won't be the first one.
