### ISSUE TITLE
model issues while porting the Carsequencing instances

### ISSUE THREAD

**Issue by SeppiaBrilla** [conjure-cp/EssenceCatalog#8]
While porting the instances to solve issue #5, I noticed that the folder CarSequencing contains 2 models: one called ```repair.essence``` and the other called ```001-CarSequencing.essence```. The second one seems, to me, the correct one to port over. However, the instances files contain extra variables. What should be the correct way to address them?
![image](https://github.com/conjure-cp/EssenceCatalog/assets/48368404/96d6fa10-bf3f-43fb-890c-3be73a21ae08)

**Comment by ozgurakgun** [comment]
it won't be the repair one, that is to do with AutoIG. can you please create an AutoIG directory inside the car-sequencing dir and move the repair model into that? this way the scripts won't pick it up.

**Comment by ozgurakgun** [comment]
I think this is now sorted, please reopen if not
