### ISSUE TITLE
model issues while porting the FixedLengthErrorCorrectingCode instances

### ISSUE THREAD

**Issue by SeppiaBrilla** [conjure-cp/EssenceCatalog#9]
While porting the instances to solve issue #5, I noticed that the folder FixedLengthErrorCorrectingCode contains a model with different input from the ones specified in the instances. As for issue #8, what is the correct way to proceed?
![image](https://github.com/conjure-cp/EssenceCatalog/assets/48368404/b28938af-1fb8-426f-91cf-cbb6e2e62f64)

Moreover, this model has a different definition from the one present in the Catalog which has the variable ```Character``` uncommented instead of ```nbCharachters``` and does not define ```maxDist```. I guess that for the ```Character``` we should proceed as commented in the open PR regarding the port. What should we do for  ```maxDist``` instead?
![image](https://github.com/conjure-cp/EssenceCatalog/assets/48368404/43a11225-070d-4cab-844f-376651fa0f5b)

**Comment by ozgurakgun** [comment]
We should probably match the format of the instances, but I am not totally sure.

**Comment by ndangtt** [comment]
I just checked the model and they seem to match the instances:

```
given nbCharacter : int(1..)
letting Character be domain int(1..nbCharacter)

given maxDist       : int(1..) ,        $ maxDist is the maximum distance between two characters
      codeWordLength : int(1..),
      numOfCodeWords : int(1..)

letting Index be domain int(1..codeWordLength),
        String be domain function (total) Index --> Character

given dist : function (total) (Character, Character) --> int(0..maxDist),
      minDist : int(0..maxDist * codeWordLength)
```

When we do `grep`, some variables won't show (e.g., `codeWordLength`), but they are there in the model.

**Comment by ozgurakgun** [comment]
I chose to go with the int version @SeppiaBrilla, but the old instances need to be updated now. 

I made two dirs under params: params/literature and params/generated. Can you please update the params/literature ones to use integers 1..n (where n is the size of the enum type)
